# Default values for node projects.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
rollingUpdate:
  maxunavailable: 0
image:
  repository: 986794016656.dkr.ecr.eu-west-2.amazonaws.com/y-tree-limited/burrow
  tag: 1.3.6
  pullPolicy: IfNotPresent

# define environment variables here as a map of key: value

# enable this flag to use knative serve to deploy the app
knativeDeploy: false

service:
  name: burrow
  type: ClusterIP
  externalPort: 80
  internalPort: 8000
  annotations:
    fabric8.io/expose: "false"

resources:
  limits:
    cpu: 800m
    memory: 512Mi
  requests:
    cpu: 800m
    memory: 512Mi

probePath: /v3/kafka
livenessProbe:
  initialDelaySeconds: 180
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
readinessProbe:
  failureThreshold: 1
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1


